import colors from "../../assets/theme/colors";

let data = [
  {
    id: 0,
    iconColor: colors.cardIconColorOne,
    backgroundColor: colors.musicBackgroundColorOne,
    musicTitle: 'Lorem Ipsum dolor sit amet consectetur',
    musicDescription: 'Fusce id velit sagittis',
    time: '05:17',
  },
  {
    id: 1,
    iconColor: colors.pink,
    backgroundColor: colors.musicBackgroundColorFour,
    musicTitle: 'Lorem Ipsum dolor sit amet consectetur',
    musicDescription: 'Fusce id velit sagittis',
    time: '05:17',
  },
  {
    id: 2,
    iconColor: colors.green,
    backgroundColor: colors.musicBackgroundColorTwo,
    musicTitle: 'Lorem Ipsum dolor sit amet consectetur',
    musicDescription: 'Fusce id velit sagittis',
    time: '05:17',
  },
  {
    id: 3,
    iconColor: colors.blue,
    backgroundColor: colors.musicBackgroundColorThree,
    musicTitle: 'Lorem Ipsum dolor sit amet consectetur',
    musicDescription: 'Fusce id velit sagittis',
    time: '05:17',
  },
  {
    id: 4,
    iconColor: colors.chromeColor,
    backgroundColor: colors.musicBackgroundColorFive,
    musicTitle: 'Lorem Ipsum dolor sit amet consectetur',
    musicDescription: 'Fusce id velit sagittis',
    time: '05:17',
  },
  {
    id: 5,
    iconColor: colors.orange,
    backgroundColor: colors.musicBackgroundColorSix,
    musicTitle: 'Lorem Ipsum dolor sit amet consectetur',
    musicDescription: 'Fusce id velit sagittis',
    time: '05:17',
  },  
  {
    id: 6,
    iconColor: colors.cardIconColorOne,
    backgroundColor: colors.musicBackgroundColorOne,
    musicTitle: 'Lorem Ipsum dolor sit amet consectetur',
    musicDescription: 'Fusce id velit sagittis',
    time: '05:17',
  },
  {
    id: 7,
    iconColor: colors.pink,
    backgroundColor: colors.musicBackgroundColorFour,
    musicTitle: 'Lorem Ipsum dolor sit amet consectetur',
    musicDescription: 'Fusce id velit sagittis',
    time: '05:17',
  },
  {
    id: 8,
    iconColor: colors.green,
    backgroundColor: colors.musicBackgroundColorTwo,
    musicTitle: 'Lorem Ipsum dolor sit amet consectetur',
    musicDescription: 'Fusce id velit sagittis',
    time: '05:17',
  },
  {
    id: 9,
    iconColor: colors.blue,
    backgroundColor: colors.musicBackgroundColorThree,
    musicTitle: 'Lorem Ipsum dolor sit amet consectetur',
    musicDescription: 'Fusce id velit sagittis',
    time: '05:17',
  },
  {
    id: 10,
    iconColor: colors.chromeColor,
    backgroundColor: colors.musicBackgroundColorFive,
    musicTitle: 'Lorem Ipsum dolor sit amet consectetur',
    musicDescription: 'Fusce id velit sagittis',
    time: '05:17',
  },
  {
    id: 11,
    iconColor: colors.orange,
    backgroundColor: colors.musicBackgroundColorSix,
    musicTitle: 'Lorem Ipsum dolor sit amet consectetur',
    musicDescription: 'Fusce id velit sagittis',
    time: '05:17',
  },  
];

export default data