export default {
  splashScreenImage: require('../assets/images/splashScreen.jpg'),
  backgroundImage: require('../assets/images/backgroundImage.png'),
  tvImage: require('../assets/images/tvImage.webp'),
  dvdImage: require('../assets/images/dvdImage.png'),
  appletImage: require('../assets/images/appleTV.png'),
  rokuImage: require('../assets/images/rokuImage.webp'),
  projectImage: require('../assets/images/projectorImage.png'),
  setellingImage: require('../assets/images/setelliteImage.png'),
  cromeCastImage: require('../assets/images/cromeCastImage.png'),
  avrImage: require('../assets/images/avrImage.png'),
  buttonCircle: require('../assets/images/buttonCircle.png'),
  buttonRectangle: require('../assets/images/buttonRectangle.png'),
  buttonMaxHeigthRectangle: require('../assets/images/buttonMaxHeightRectangle.png'),
  buttonMaxWidthRectangle: require('../assets/images/buttonMaxWidthRectangle.png'),
  defaultImage: require('../assets/images/home.jpg'),
};
