const routeNames = {
  //Auth stack screens
  SPLASH: 'Splash',
  LOGIN: 'Login',
  FORGOTPASSWORD: 'Forgot Password',
  OTPSCREEN: ' Otp Screen',
  LOADING: 'Loading',

  //Home Stack Screens
  HOME: 'Home',
  HOMEVIEW: 'HomeView',
  ADDHOME: 'Add Home',
  SWEETHOME: 'Sweet_Home',
  APPDRAWERNAVIGATION: 'AppDrawerNavigation',
  LIGHT: 'Light',
  RGBW: 'RGBW',
  BOTTOMTABNAVIGATOR: 'BottomTabNavigator',
  SECONDBOTTOMTABNAVIGATOR: 'SecondBottomTabNavigator',
  DMX: 'Dmx',
  HVAC: 'Hvac',
  ZAUDIO: 'Z-Audio',
  CURTAIN: 'Curtain',
  TESTCURTAIN: 'TestCurtain',
  FAN: 'Fan',
  OTHERCONTROL: 'OtherControl',
  IRRIGATION: 'Irrigation',
  MEDIA: 'Media',
  MEDIASETTING: 'MediaSetting',
  MEDIAOTHERSETTING: 'MediaOtherSetting',
  CAMERA: 'Camera',
  CAMERASETTING: 'CameraSettings',
  LIGHTSETTING: 'LightSetting',
  RGBWCOMPONENT: 'RgbwComponent',
  FAHRENHEITSCREEN: 'FahrenheitScreen',
  CELSIUSSCREEN: 'CelsiusScreen',
  ACSETTING: 'AcSetting',
  MUSICSETTING: 'MusicSetting',
  MOODSCREEN: 'MoodScreen',
  MODSETTING: 'MoodSetting',
  FANSETTING: 'FanSetting',
  IRRIGATIONSETTING: 'IRRIGATIONSETTING',
  WATCHTVSCREEN: 'WatchTvScreen',
  WATCHDVD: 'WatchDVD',
  WATCHAPPLETV: 'WatchAppleTV',
  WATCHROKU: 'WatchRoku',
  WATCHSATELLITE: 'WatchSatellite',
  SCENCECONTROLSETTINGS: 'ScenceControlSettings',
};

export default routeNames;
