const types = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGIN: 'LOGIN',
  FORGOTPASSWORD: 'FORGOTPASSWORD',
  RESETPASSWORD: 'RESET PASSWORD',

  CLEAR_REDUX_STATE: 'CLEAR_REDUX_STATE',
  NO_INTERNET: 'NO_INTERNET',

  SET_AREAZONEID: 'SET AREA ZONE ID',
  SET_ZONEID: 'SET ZONE ID',
  GET_RGBW_DATA_BYID: 'GET RGBW DATA BY ID',
};

export default types;
