const types = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGIN: 'LOGIN',

  CLEAR_REDUX_STATE: 'CLEAR_REDUX_STATE',
  NO_INTERNET: 'NO_INTERNET',
};

export default types;
