import colors from '../../assets/theme/colors';
import {
  BOTTOMTABNAVIGATOR,
  CAMERA,
  CURTAIN,
  FAN,
  HVAC,
  IRRIGATION,
  MEDIA,
  MOODSCREEN,
  OTHERCONTROL,
  SECONDBOTTOMTABNAVIGATOR,
  ZAUDIO,
} from '../../constants/routeNames';

let data = [
  {
    id: 0,
    title: 'light',
    type: 'fa6',
    name: 'lightbulb',
    color: colors.iconSecondColor,
    screen: BOTTOMTABNAVIGATOR,
  },
  {
    id: 1,
    title: 'rgbw',
    type: 'fa6',
    name: 'lightbulb',
    color: colors.iconThirdColor,
    screen: SECONDBOTTOMTABNAVIGATOR,
  },
  {
    id: 3,
    title: 'dmx',
    type: 'entypo',
    name: 'sound-mix',
    color: colors.iconForthColor,
    alert: 'Screen not available',
  },
  {
    id: 4,
    title: 'hvac',
    type: 'fa6',
    name: 'snowflake',
    color: colors.iconFifthColor,
    screen: HVAC,
  },
  {
    id: 5,
    title: 'z-audio',
    type: 'fa6',
    name: 'music',
    color: colors.iconSixthColor,
    screen: ZAUDIO,
  },
  {
    id: 6,
    title: 'curtain',
    type: 'materialCommunity',
    name: 'curtains',
    color: colors.iconSeventhColor,
    screen: CURTAIN,
  },
  {
    id: 7,
    title: 'moods',
    type: 'fa6',
    name: 'fan',
    color: colors.iconFifthColor,
    screen: MOODSCREEN,
  },
  {
    id: 8,
    title: 'fan',
    type: 'fa6',
    name: 'fan',
    color: colors.iconForthColor,
    screen: FAN,
  },
  {
    id: 9,
    title: 'other control',
    type: 'fa6',
    name: 'gamepad',
    color: colors.iconThirdColor,
    screen: OTHERCONTROL,
  },
  {
    id: 10,
    title: 'irrigation',
    type: 'fa',
    name: 'leaf',
    color: colors.iconSixthColor,
    screen: IRRIGATION,
  },
  {
    id: 11,
    title: 'media',
    type: 'fa6',
    name: 'photo-film',
    color: colors.iconSeventhColor,
    screen: MEDIA,
  },
  {
    id: 12,
    title: 'camera',
    type: 'fa6',
    name: 'video',
    color: colors.iconSecondColor,
    screen: CAMERA,
  },
];
export default data;
