import colors from "../../assets/theme/colors";
import { BOTTOMTABNAVIGATOR, HVAC, SECONDBOTTOMTABNAVIGATOR } from "../../constants/routeNames";

let data = [
  {
    id: 0,
    title: 'light',
    type: 'fa6',
    name: 'lightbulb',
    color: colors.iconSecondColor,
    screen: BOTTOMTABNAVIGATOR,
  },
  {
    id: 1,
    title: 'rgbw',
    type: 'fa6',
    name: 'lightbulb',
    color: colors.iconThirdColor,
    screen: SECONDBOTTOMTABNAVIGATOR,
  },
  {
    id: 3,
    title: 'dmx',
    type: 'entypo',
    name: 'sound-mix',
    color: colors.iconForthColor,
    alert: 'DMX card pressed',
  },
  {
    id: 4,
    title: 'hvac',
    type: 'fa6',
    name: 'snowflake',
    color: colors.iconFifthColor,
    screen: HVAC,
  },
  {
    id: 5,
    title: 'z-audio',
    type: 'fa6',
    name: 'music',
    color: colors.iconSixthColor,
    alert: 'Z-AUDIO card pressed',
  },
  {
    id: 6,
    title: 'curtain',
    type: 'materialCommunity',
    name: 'curtains',
    color: colors.iconSeventhColor,
    alert: 'Curtain card pressed',
  },
  {
    id: 7,
    title: 'moods',
    type: 'fa6',
    name: 'fan',
    color: colors.iconFifthColor,
    alert: 'Moods card pressed',
  },
  {
    id: 8,
    title: 'fan',
    type: 'fa6',
    name: 'fan',
    color: colors.iconForthColor,
    alert: 'Fan card pressed',
  },
  {
    id: 9,
    title: 'other control',
    type: 'materialCommunity',
    name: 'controller-classic',
    color: colors.iconThirdColor,
    alert: 'Other Control card pressed',
  },
  {
    id: 10,
    title: 'irrigation',
    type: 'fa',
    name: 'leaf',
    color: colors.iconSixthColor,
    alert: 'Irrigation card pressed',
  },
  {
    id: 11,
    title: 'media',
    type: 'fa6',
    name: 'photo-film',
    color: colors.iconSeventhColor,
    alert: 'Media card pressed',
  },
  {
    id: 12,
    title: 'camera',
    type: 'fa6',
    name: 'video',
    color: colors.iconSecondColor,
    alert: 'Camera card pressed',
  },
];
export default data;
