import React from 'react';
import AppDrawerNavigation from './AppDrawerNavigation';
import BottomTabNavigator from './BottomTabNavigator';
import SecondBottomTabNavigator from './SecondBottomTabNavigator';
import routeNames from './../constants/routeNames';
import screens from './../screens/index';

export default function HomeStack(Stack) {
  const navigationOptions = {
    headerShown: false,
  };
  return (
    <>
      <Stack.Screen
        name={routeNames.HOME}
        component={screens.Home}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.HOMEVIEW}
        component={screens.HomeView}
        options={navigationOptions}
      />
      <Stack.Screen name={routeNames.ADDHOME} component={screens.AddHome} />
      <Stack.Screen
        name={routeNames.SWEETHOME}
        component={screens.SweetHome}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.APPDRAWERNAVIGATION}
        component={AppDrawerNavigation}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.BOTTOMTABNAVIGATOR}
        component={BottomTabNavigator}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.SECONDBOTTOMTABNAVIGATOR}
        component={SecondBottomTabNavigator}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.LIGHTSETTING}
        component={screens.LightSetting}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.RGBWCOMPONENT}
        component={screens.RgbwComponent}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.HVAC}
        component={screens.Hvac}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.FAHRENHEITSCREEN}
        component={screens.FahrenheitScreen}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.CELSIUSSCREEN}
        component={screens.CelsiusScreen}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.ACSETTING}
        component={screens.AcSettings}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.ZAUDIO}
        component={screens.ZAudio}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.MUSICSETTING}
        component={screens.MusicSetting}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.CURTAIN}
        component={screens.Curtain}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.TESTCURTAIN}
        component={screens.TestCurtain}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.MOODSCREEN}
        component={screens.MoodScreen}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.MODSETTING}
        component={screens.MoodSetting}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.FAN}
        component={screens.Fan}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.FANSETTING}
        component={screens.FanSetting}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.OTHERCONTROL}
        component={screens.OtherControl}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.IRRIGATIONSETTING}
        component={screens.IrrigationSetting}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.MEDIA}
        component={screens.Media}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.MEDIASETTING}
        component={screens.MediaSetting}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.MEDIAOTHERSETTING}
        component={screens.MediaOtherSettings}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.WATCHTVSCREEN}
        component={screens.WatchTVScreen}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.WATCHDVD}
        component={screens.WatchDVD}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.WATCHAPPLETV}
        component={screens.WatchAppleTV}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.WATCHROKU}
        component={screens.WatchRoku}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.WATCHSATELLITE}
        component={screens.WatchSatellite}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.IRRIGATION}
        component={screens.Irrigation}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.CAMERA}
        component={screens.Camera}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.CAMERASETTING}
        component={screens.CameraSettings}
        options={navigationOptions}
      />
      <Stack.Screen
        name={routeNames.SCENCECONTROLSETTINGS}
        component={screens.ScenceControlSettings}
        options={navigationOptions}
      />
    </>
  );
}
